[package]
name = "defaults-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
better-core.workspace = true
defaults-platform.workspace = true
defaults-store.workspace = true
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
manager-core.workspace = true
manager-platform.workspace = true
serde_json.workspace = true
tempfile.workspace = true
